# Generated by Django 6.0 on 2025-12-21 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bin_id'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('tracking_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('unregistered', 'Unregistered'), ('registered', 'Registered'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='unregistered', max_length=20)),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='inbound.bin')),
            ],
            options={
                'ordering': ['-time_in'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('updated', 'Updated'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], max_length=50)),
                ('user', models.CharField(default='system', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='inbound.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
