# Generated by Django 6.0 on 2025-12-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='time_registered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
