# Generated by Django 6.0 on 2025-12-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0002_shipment_time_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('updated', 'Updated'), ('dissociated', 'Dissociated'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('unregistered', 'Unregistered'), ('registered', 'Registered'), ('picked-up', 'Picked Up'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='unregistered', max_length=20),
        ),
    ]
