# Generated by Django 6.0 on 2025-12-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0003_alter_auditlog_action_alter_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='manifested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='inbound.bin'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('manifested', 'Manifested'), ('unregistered', 'Unregistered'), ('registered', 'Registered'), ('picked-up', 'Picked Up'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='unregistered', max_length=20),
        ),
    ]
