# Generated by Django 6.0 on 2025-12-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0004_shipment_manifested_alter_shipment_bin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='time_registered',
        ),
    ]
