# Generated by Django 6.0 on 2025-12-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0007_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('manifested', 'Manifested'), ('putaway', 'Putaway'), ('picklist-created', 'Picklist Created'), ('picked', 'Picked'), ('unregistered', 'Unregistered'), ('registered', 'Registered'), ('picked-up', 'Picked Up'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='unregistered', max_length=20),
        ),
    ]
